# Generated by Django 2.2.4 on 2019-08-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_auhor',
            new_name='comment_author',
        ),
    ]
